#index: #zay ao am @routecontroller  de lé name
#   path: / #zay tina atao chemin-ny
#   controller: App\Controller\DefaultController::index #index(zay ao amfunction tina apesaina am controller)

security_registration:
   path: /registration
   controller: App\Controller\SecurityController::registration

security_login:
   path: /connexion
   controller: App\Controller\SecurityController::login

home:
   path: /
   controller: App\Controller\UserController::home

security_logout:
   path: /deconnexion
   controller: App\Controller\UserController::home

liste:
   path: /listeU
   controller: App\Controller\UserController::ShowUser

commande:
   path: /commande
   controller: App\Controller\CommandeController::index
client:
   path: /client
   controller: App\Controller\ClientController::index

fournisseur:
      path: /fournisseur
      controller: App\Controller\FournisseurController::index 

tableau_de_bord:
      path: /dashboard
      controller: App\Controller\UserController::Showdashboard 